[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "open-duck-mini-runtime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-bno055>=5.4.22",
    "numpy>=2.4.6",
    "openai>=2.41.0",
    "pypot",
    "rustypot>=1.5.0",
    "scipy>=1.17.1",
]

[tool.uv.sources]
pypot = { git = "https://github.com/pollen-robotics/pypot", rev = "support-feetech-sts3215" }

[tool.setuptools.package-dir]
"" = "mini_bdx_runtime"

[tool.setuptools.packages.find]
where = ["mini_bdx_runtime"]
